/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import acceso_a_datos.InmuebleData;
import inmobiliaria.entidades.Inmueble;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Agente Sosa
 */
public class AdministracionInmuebleCBM extends javax.swing.JInternalFrame {

    DefaultTableModel modelo = new DefaultTableModel();
    
    public AdministracionInmuebleCBM() {
        initComponents();
        cargarCombo();
        cargarCabecera();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbusqueda = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtInmuebles = new javax.swing.JTable();
        jbsalir = new javax.swing.JButton();
        jbrestablecer = new javax.swing.JButton();
        jbguardarcambios = new javax.swing.JButton();
        jbeliminar = new javax.swing.JButton();
        jtLetra = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setText("CONSULTA ALTA  BAJA MODIFICIACION");

        jLabel2.setText("BUSCAR POR:");

        jcbusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbusquedaActionPerformed(evt);
            }
        });

        jtInmuebles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtInmuebles);

        jbsalir.setText("SALIR");
        jbsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsalirActionPerformed(evt);
            }
        });

        jbrestablecer.setText("RESTABLECER");
        jbrestablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbrestablecerActionPerformed(evt);
            }
        });

        jbguardarcambios.setText("GUARDAR CAMBIOS");
        jbguardarcambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbguardarcambiosActionPerformed(evt);
            }
        });

        jbeliminar.setText("ELIMINAR");

        jtLetra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtLetraKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(187, 187, 187)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(jtLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(162, 162, 162)
                            .addComponent(jbrestablecer)
                            .addGap(18, 18, 18)
                            .addComponent(jbguardarcambios)
                            .addGap(18, 18, 18)
                            .addComponent(jbeliminar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbsalir))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(145, 145, 145)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbrestablecer)
                    .addComponent(jbguardarcambios)
                    .addComponent(jbeliminar)
                    .addComponent(jbsalir))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbsalirActionPerformed

    private void jbrestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbrestablecerActionPerformed
//        borrarDatos();
//        cargarTabla();
//        jtpalabra.setText("");
    }//GEN-LAST:event_jbrestablecerActionPerformed

    private void jbguardarcambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbguardarcambiosActionPerformed

//        InmuebleData inquidata = new InquilinoData();
//
//        int fila = jtinquilinos.getSelectedRow();
//
//        Inquilino i = new Inquilino();
//
//        i.setIdInquilino((int)jtinquilinos.getValueAt(fila, 0));
//        i.setNombre((String)jtinquilinos.getValueAt(fila,1));
//        i.setApellido((String)jtinquilinos.getValueAt(fila,2));
//        i.setCuit((String)jtinquilinos.getValueAt(fila,3));
//        i.setLugarTrabajo((String)jtinquilinos.getValueAt(fila,4));
//        i.setNombreGarante((String)jtinquilinos.getValueAt(fila,5));
//        i.setDniGarante((String)jtinquilinos.getValueAt(fila,6));
//
//        inquidata.actualizarInquilino(i);
//        borrarDatos();
//        jtpalabra.setText("");
//        cargarTabla();
    }//GEN-LAST:event_jbguardarcambiosActionPerformed

    private void jcbusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbusquedaActionPerformed
        
        
        
    }//GEN-LAST:event_jcbusquedaActionPerformed

    private void jtLetraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtLetraKeyReleased
        borrarDatos();
        String letra = (String)jcbusqueda.getSelectedItem();
        InmuebleData inmo = new InmuebleData();
        
        switch (letra) {
            case "id_inmueble":
                for (Inmueble i : inmo.listarInmuebles()) {
                    if (String.valueOf(i.getIdInmueble()).startsWith(jtLetra.getText())) {
                        modelo.addRow(new Object[]{i.getIdInmueble(), i.getDireccion(), i.getAltura(), i.getTipo(), i.getSuperficie(), i.getPrecio(), i.getDisponibilidad(), i.getPropietario().getIdPropietario(), i.isEstado()});
                    }
                }
                break;
            case "direccion":
                for (Inmueble i : inmo.listarInmuebles()){
                    if (String.valueOf(i.getDireccion()).toLowerCase().startsWith(jtLetra.getText().toLowerCase())) {
                        modelo.addRow(new Object[]{i.getIdInmueble(), i.getDireccion(), i.getAltura(), i.getTipo(), i.getSuperficie(), i.getPrecio(), i.getDisponibilidad(), i.getPropietario().getIdPropietario(), i.isEstado()});
                    }
                }
                break;
        }
    }//GEN-LAST:event_jtLetraKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbeliminar;
    private javax.swing.JButton jbguardarcambios;
    private javax.swing.JButton jbrestablecer;
    private javax.swing.JButton jbsalir;
    private javax.swing.JComboBox<String> jcbusqueda;
    private javax.swing.JTable jtInmuebles;
    private javax.swing.JTextField jtLetra;
    // End of variables declaration//GEN-END:variables

    public void cargarCombo (){
        
        jcbusqueda.addItem("id_inmueble");
        jcbusqueda.addItem("direccion");
        jcbusqueda.addItem("altura");
        jcbusqueda.addItem("tipo");
        jcbusqueda.addItem("superficie");
        jcbusqueda.addItem("precio");
        jcbusqueda.addItem("disponibilidad");
        jcbusqueda.addItem("id_propietario");
        jcbusqueda.addItem("estado");
        
    }
    
    public void cargarCabecera (){
        
        modelo.addColumn("id_inmueble");
        modelo.addColumn("direccion");
        modelo.addColumn("altura");
        modelo.addColumn("tipo");
        modelo.addColumn("superficie");
        modelo.addColumn("precio");
        modelo.addColumn("disponibilidad");
        modelo.addColumn("id_propietario");
        modelo.addColumn("estado");
        jtInmuebles.setModel(modelo);
        
    }

    private void borrarDatos() {

        int f = jtInmuebles.getRowCount() - 1; //obtengo total de filas de la tabla

        for (; f >= 0; f--) { //recorro filas para borrar 1 por 1 en iteracion.

            modelo.removeRow(f);// remuevo valor por indice en la tabla "jcTable"
        }
    }
    
}
