/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import acceso_a_datos.InquilinoData;
import inmobiliaria.entidades.Inquilino;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author santy
 */
public class AdministracionInquilino extends javax.swing.JInternalFrame {

    private InquilinoData inquiData = new InquilinoData(); 
    private Inquilino inquiActual = null;
    
    public AdministracionInquilino() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPFondo = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jtCuit = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtApellido = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtLugarTrabajo = new javax.swing.JTextField();
        jrb1 = new javax.swing.JRadioButton();
        jrb2 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtNombreGarante = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtDniGarante = new javax.swing.JTextField();
        jbIngresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1060, 660));
        setMinimumSize(new java.awt.Dimension(1080, 630));
        setPreferredSize(new java.awt.Dimension(1060, 660));

        jPFondo.setBackground(new java.awt.Color(255, 255, 255));
        jPFondo.setMaximumSize(new java.awt.Dimension(1076, 630));
        jPFondo.setMinimumSize(new java.awt.Dimension(1080, 670));
        jPFondo.setPreferredSize(new java.awt.Dimension(1080, 670));
        jPFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("CUIT");
        jPFondo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, -1, 30));

        jtCuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCuitActionPerformed(evt);
            }
        });
        jPFondo.add(jtCuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, 360, 30));

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("NOMBRE");
        jPFondo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, -1, 30));

        jtNombre.setForeground(new java.awt.Color(51, 51, 51));
        jPFondo.add(jtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 360, 30));

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("APELLIDO");
        jPFondo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, -1, 30));
        jPFondo.add(jtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, 360, 30));

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("LUGAR DE TRABAJO");
        jPFondo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, -1, 30));

        jtLugarTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtLugarTrabajoActionPerformed(evt);
            }
        });
        jPFondo.add(jtLugarTrabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 270, 270, 30));

        jrb1.setBackground(new java.awt.Color(204, 204, 204));
        jrb1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jrb1.setText("ACTIVO ");
        jrb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb1ActionPerformed(evt);
            }
        });
        jPFondo.add(jrb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 310, 110, -1));

        jrb2.setBackground(new java.awt.Color(204, 204, 204));
        jrb2.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jrb2.setText("INACTIVO");
        jrb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb2ActionPerformed(evt);
            }
        });
        jPFondo.add(jrb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 310, 110, -1));

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("DATOS DEL GARANTE");
        jPFondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, -1, -1));

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("NOMBRE ");
        jPFondo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, -1, 30));

        jtNombreGarante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNombreGaranteActionPerformed(evt);
            }
        });
        jPFondo.add(jtNombreGarante, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, 360, 30));

        jLabel10.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("DNI ");
        jPFondo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, -1, 30));

        jtDniGarante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtDniGaranteActionPerformed(evt);
            }
        });
        jPFondo.add(jtDniGarante, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 460, 360, 30));

        jbIngresar.setBackground(new java.awt.Color(153, 153, 153));
        jbIngresar.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 22)); // NOI18N
        jbIngresar.setForeground(new java.awt.Color(51, 51, 51));
        jbIngresar.setText("INGRESAR");
        jbIngresar.setBorderPainted(false);
        jbIngresar.setFocusPainted(false);
        jbIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIngresarActionPerformed(evt);
            }
        });
        jPFondo.add(jbIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 500, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/LABEL BUSCAR INQUILINO.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(576, 1280));
        jLabel1.setMinimumSize(new java.awt.Dimension(576, 1280));
        jLabel1.setPreferredSize(new java.awt.Dimension(576, 1280));
        jPFondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 510, 630));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/Sis gestion.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPFondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 620, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 1027, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIngresarActionPerformed

        try {
            String cuit = jtCuit.getText();
            String nombre = jtNombre.getText();
            String apellido = jtApellido.getText();
            String lugarDeTrabajo = jtLugarTrabajo.getText();
            String nombreGarante = jtNombreGarante.getText();
            String dniGarante = jtDniGarante.getText();
            boolean estado = jrb1.isSelected();

            if (( validarCampoNumerico(jtCuit)) && (validarCampoNumerico(jtDniGarante)) && (validarCampoTexto(jtNombre)) && (validarCampoTexto(jtApellido)) && (validarCampoTexto(jtNombreGarante)) && (validarCampoTexto(jtLugarTrabajo))) {
                //creo inquilino

                Inquilino inquilino = new Inquilino (cuit,nombre, apellido, lugarDeTrabajo, nombreGarante, dniGarante, estado);
                inquiData.insertarInquilino(inquilino);

                limpiarCampos();
            }

        } catch (NumberFormatException nfe) {

        }

    }//GEN-LAST:event_jbIngresarActionPerformed

    private void jtDniGaranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtDniGaranteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtDniGaranteActionPerformed

    private void jtNombreGaranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNombreGaranteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNombreGaranteActionPerformed

    private void jrb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb2ActionPerformed
        jrb1.setSelected(false);
        jrb2.setSelected(true);
    }//GEN-LAST:event_jrb2ActionPerformed

    private void jrb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb1ActionPerformed
        jrb1.setSelected(true);
        jrb2.setSelected(false);

    }//GEN-LAST:event_jrb1ActionPerformed

    private void jtCuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCuitActionPerformed

    }//GEN-LAST:event_jtCuitActionPerformed

    private void jtLugarTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtLugarTrabajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtLugarTrabajoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPFondo;
    private javax.swing.JButton jbIngresar;
    private javax.swing.JRadioButton jrb1;
    private javax.swing.JRadioButton jrb2;
    private javax.swing.JTextField jtApellido;
    private javax.swing.JTextField jtCuit;
    private javax.swing.JTextField jtDniGarante;
    private javax.swing.JTextField jtLugarTrabajo;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtNombreGarante;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos() {

        jtCuit.setText("");
        jtApellido.setText("");
        jtNombre.setText("");
        jtDniGarante.setText("");
        jtLugarTrabajo.setText(""); 
        jtNombreGarante.setText("");
        
    }

       public boolean validarCampoTexto(JTextField textfield) {
        if (textfield.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "No pueden haber campos vacios.");
            textfield.requestFocus();
            return false;
        } else if (!textfield.getText().matches("^[a-zA-ZáéíóúÁÉÍÓÚüÜñÑ'\\s]+$")) {
            JOptionPane.showMessageDialog(null, "El campo solo puede contener letras.");
            textfield.setText("");
            textfield.requestFocus();
            return false;
        }
        return true;
    }
       
         public boolean validarCampoNumerico(JTextField textfield) {
        if (textfield.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "No pueden haber campos vacios.");
            textfield.requestFocus();
            return false;

        } else if (!textfield.getText().matches("^[0-9]+$")) {
            JOptionPane.showMessageDialog(null, "El campo solo puede contener numeros.");
            textfield.setText("");
            textfield.requestFocus();
            return false;
        }
        return true;
    }
}
